CREATE TABLE rankings (
    rankingid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playerid NUMBER NOT NULL,
    rank_position NUMBER NOT NULL,
    date_updated DATE NOT NULL,
    CONSTRAINT fk_player
        FOREIGN KEY (playerid)
        REFERENCES players (playerid)
);