CREATE TABLE winners (
    winner_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id NUMBER NOT NULL,
    tournament_id NUMBER NOT NULL,
    CONSTRAINT fk_winning_player
        FOREIGN KEY (player_id)
        REFERENCES players (player_id),
    CONSTRAINT fk_winning_tournament
        FOREIGN KEY (tournament_id)
        REFERENCES tournaments (tournament_id)
);