CREATE TABLE winners (
    winner_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id NUMBER NOT NULL,
    tournament_id NUMBER NOT NULL,
    CONSTRAINT fk_winning_player
        FOREIGN KEY (player_id)
        REFERENCES players (player_id),
    CONSTRAINT fk_winning_tournament
        FOREIGN KEY (tournament_id)
        REFERENCES tournaments (tournament_id)
);

INSERT INTO winners (player_id, tournament_id) VALUES (6, 1);
INSERT INTO winners (player_id, tournament_id) VALUES (33, 2);
INSERT INTO winners (player_id, tournament_id) VALUES (19, 3);
INSERT INTO winners (player_id, tournament_id) VALUES (20, 4);
INSERT INTO winners (player_id, tournament_id) VALUES (9, 5);
INSERT INTO winners (player_id, tournament_id) VALUES (49, 6);
INSERT INTO winners (player_id, tournament_id) VALUES (22, 7);
INSERT INTO winners (player_id, tournament_id) VALUES (1, 8);
INSERT INTO winners (player_id, tournament_id) VALUES (20, 9);
INSERT INTO winners (player_id, tournament_id) VALUES (7, 10);
INSERT INTO winners (player_id, tournament_id) VALUES (7, 11);
INSERT INTO winners (player_id, tournament_id) VALUES (17, 12);
INSERT INTO winners (player_id, tournament_id) VALUES (16, 13);
INSERT INTO winners (player_id, tournament_id) VALUES (36, 14);
INSERT INTO winners (player_id, tournament_id) VALUES (17, 15);
INSERT INTO winners (player_id, tournament_id) VALUES (6, 16);
INSERT INTO winners (player_id, tournament_id) VALUES (18, 17);
INSERT INTO winners (player_id, tournament_id) VALUES (24, 18);
INSERT INTO winners (player_id, tournament_id) VALUES (8, 19);
INSERT INTO winners (player_id, tournament_id) VALUES (9, 20);
INSERT INTO winners (player_id, tournament_id) VALUES (24, 21);
INSERT INTO winners (player_id, tournament_id) VALUES (23, 22);
INSERT INTO winners (player_id, tournament_id) VALUES (40, 23);
INSERT INTO winners (player_id, tournament_id) VALUES (43, 24);
INSERT INTO winners (player_id, tournament_id) VALUES (17, 25);
INSERT INTO winners (player_id, tournament_id) VALUES (26, 26);
INSERT INTO winners (player_id, tournament_id) VALUES (13, 27);
INSERT INTO winners (player_id, tournament_id) VALUES (26, 28);
INSERT INTO winners (player_id, tournament_id) VALUES (46, 29);
INSERT INTO winners (player_id, tournament_id) VALUES (5, 30);
INSERT INTO winners (player_id, tournament_id) VALUES (9, 31);
INSERT INTO winners (player_id, tournament_id) VALUES (1, 32);
INSERT INTO winners (player_id, tournament_id) VALUES (1, 33);
INSERT INTO winners (player_id, tournament_id) VALUES (22, 34);
INSERT INTO winners (player_id, tournament_id) VALUES (13, 35);
INSERT INTO winners (player_id, tournament_id) VALUES (5, 36);
INSERT INTO winners (player_id, tournament_id) VALUES (21, 37);
INSERT INTO winners (player_id, tournament_id) VALUES (17, 38);
INSERT INTO winners (player_id, tournament_id) VALUES (4, 39);
INSERT INTO winners (player_id, tournament_id) VALUES (35, 40);
INSERT INTO winners (player_id, tournament_id) VALUES (16, 41);
INSERT INTO winners (player_id, tournament_id) VALUES (12, 42);
INSERT INTO winners (player_id, tournament_id) VALUES (26, 43);
INSERT INTO winners (player_id, tournament_id) VALUES (14, 44);
INSERT INTO winners (player_id, tournament_id) VALUES (5, 45);
INSERT INTO winners (player_id, tournament_id) VALUES (7, 46);
INSERT INTO winners (player_id, tournament_id) VALUES (36, 47);
INSERT INTO winners (player_id, tournament_id) VALUES (9, 48);
INSERT INTO winners (player_id, tournament_id) VALUES (19, 49);
INSERT INTO winners (player_id, tournament_id) VALUES (27, 50);
