CREATE TABLE Players (
    PlayerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    Age NUMBER(2) NOT NULL,
    country VARCHAR2(50)
);

INSERT INTO Players (first_name, last_name, age, country) VALUES ('Novak', 'Djokovic', 36, 'Serbia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Jannik', 'Sinner', 22, 'Italy');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Carlos', 'Alcaraz', 20, 'Spain');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Daniil', 'Medvedev', 28, 'Russia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Alexander', 'Zverev', 26, 'Germany');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Andrey', 'Rublev', 26, 'Russia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Holger', 'Rune', 20, 'Denmark');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Hubert', 'Hurkacz', 27, 'Poland');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Grigor', 'Dimitrov', 32, 'Bulgaria');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Caspar', 'Ruud', 25, 'Norway');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Alex', 'De Minaur', 25, 'Australia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Stefanos', 'Tsitsipas', 25, 'Greece');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Taylor', 'Fritz', 26, 'United States');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Ben', 'Shelton', 21, 'United States');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Ugo', 'Humbert', 25, 'France');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Tommy', 'Paul', 26, 'United States');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Karen', 'Khachanov', 27, 'Russia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Alexander', 'Bublik', 26, 'Kazakhstan');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Sebastian', 'Baez', 23, 'Argentina');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Mannarino', 'Adrian', 35, 'France');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Nicolas', 'Jarry', 28, 'Chile');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Francisco', 'Cerundolo', 25, 'Argentina');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Frances', 'Tiafoe', 26, 'United States');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Lorenzo', 'Musetti', 22, 'Italy');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Jan-Lennard', 'Struff', 33, 'Germany');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Tallon', 'Griekspoor', 27, 'Netherlands');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Sebastian', 'Korda', 23, 'United States');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Jiri', 'Lehecka', 22, 'Czechia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Alejandro', 'Davidovich Fokina', 24, 'Spain');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Cameron', 'Norrie', 28, 'Great Britain');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Tomas Martin', 'Etcheverry', 24, 'Argentina');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Jordan', 'Thompson', 29, 'Australia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Borna', 'Coric', 27, 'Croatia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Laslo', 'Djere', 28, 'Serbia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Felix', 'Auger-Aliassime', 23, 'Canada');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Arthur', 'Fils', 19, 'France');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Fabio', 'Marozsan', 24, 'Hungary');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Matteo', 'Arnaldi', 23, 'Italy');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Jack', 'Draper', 22, 'Great Britain');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Gael', 'Monfils', 37, 'France');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Roman', 'Safiullin', 26, 'Russia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Christopher', 'Eubanks', 27, 'United States');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Aslan', 'Karatsev', 30, 'Russia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Sebastian', 'Ofner', 27, 'Austria');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Alejandro', 'Tabilo', 26, 'Chile');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Sebastian', 'Ofner', 27, 'Austria');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Alexei', 'Popyrin', 24, 'Australia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Tomas', 'Machac', 23, 'Czechia');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Marcos', 'Giron', 30, 'United States');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Zhizhen', 'Zhang', 27, 'China');
INSERT INTO Players (first_name, last_name, age, country) VALUES ('Daniel', 'Evans', 33, 'Great Britain');