CREATE TABLE surfaces (
    surface_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surface_type VARCHAR2(50) NOT NULL UNIQUE
);

INSERT INTO surfaces (surface_type) VALUES ('Clay');
INSERT INTO surfaces (surface_type) VALUES ('Grass');
INSERT INTO surfaces (surface_type) VALUES ('Hard');
INSERT INTO surfaces (surface_type) VALUES ('Carpet');